image:
  file: Dockerfile

tasks:
  - name: Install dependencies
    command: |
      apt-get update
      apt-get install -y python3-pip
      pip3 install tensorflow-gpu==2.3.1 sentencepiece tensorflow-hub bert-tensorflow mpi4py
      
  - name: Run the code
    command: |
      python3 main.py
