tasks:
  - init: |
      python -m venv venv
      !pip install tensorflow-gpu==2.3.1
      !pip install sentencepiece
      !pip install tensorflow-hub
      !pip install bert-tensorflow
      source venv/bin/activate
      pip install --upgrade pip wheel setuptools
      python manage.py migrate
  - command: |
      source venv/bin/activate
      python manage.py runserver
  
ports:
  - port: 8000
    visibility: public
    onOpen: open-preview

vscode:
  extensions:
    - ms-python.python
